### ISSUE TITLE
hello.

### ISSUE THREAD

**Issue by imaregisteredoffender** [LunarN0v4/lunarn0v4#1]
i request u remove this repo as u clearly stole my profile. - i will get this removed forcefully if u dont comply

**Comment by LunarN0v4** [comment]
Hello, you may not request a takedown of this repo as your "work" does not fall under any DMCA originality according to [this page](https://www.artslaw.com.au/information-sheet/copyright/).  
You are directly communicating with me after I have told you that I would no longer like to receive communications with you and further legal requests should've been sent to [zeus@zeusteam.dev](mailto:zeus@zeusteam.dev).  
I will not be complying with this request and further replies will be disabled here, you are required to send me an email regarding any further legal matters.  
Otherwise, do not contact me ever again, I am sick of your harassment and I will be filing for a restraining order if you continue.  
- Nova Notepad

**Comment by LunarN0v4** [comment]
To add on for any GitHub staff members who may see this, or other people.  
ariez / meowmade / Keaton Ward / vyx is actively harassing me by sending false DMCA takedown notices, even ones with fake addresses and information (which is identify theft / fraud), this is intended to scare me into taking down something that I borrowed from one of their pages and gave them credit for, however, the "work" does not have enough originality to be considered possible for a DMCA takedown notice.  
I can provide proof of these takedowns and my real identity further if needed.  
Nova out.

**Comment by LunarN0v4** [comment]
Simply due to how stupid this issue is, alongside my anger subsiding, I will be pinning it for your enjoyment.  
Sorry Keaton that you got butthurt over me blocking you on Discord for getting my Xbox account banned from chat for a day.  
L, rest in shit.

**Comment by LunarN0v4** [comment]
To extend onto this, Keaton attempted to spam this repository with issues, however, he forgot that when my computer boots up, it bans all issues from his accounts, which I have an entire list of, even accounts he hasn't tried to use yet (thank you GitHub staff :3).  
I am going to work in implementing a restraining order, alongside getting my associated hacking group to continue Project Gamma.  
Good job Keaton, you just fucked yourself over.

**Comment by LunarN0v4** [comment]
kittys never win  
nova always win

**Comment by LunarN0v4** [comment]
That demeanor changed fast huh  
![image](https://github.com/LunarN0v4/lunarn0v4/assets/71067215/2b396351-46eb-4131-ac77-19d67b18f9d8)
